from pathlib import Path
import json,base64,html,hashlib,sqlite3
r=json.loads(Path('followup_results.json').read_text());log=json.loads(Path('followup_memory_retrieval.json').read_text())[-1]
summary='Excluding adld3p and urin1 increases the exploratory propensity-weighted association at every clipping threshold. The risk difference rises by 0.505–0.543 percentage points and the risk ratio by 0.0167–0.0180. All 5,735 patients remain (2,184 RHC; 3,551 No RHC).'
warning='Deleting potential confounders is a sensitivity exercise, not a repair that establishes causal validity. These are associations with supplied 30-day mortality, not causal effects. No confidence intervals were calculated for this follow-up, and no prior intervals are reused. Differences between specifications have no calculated uncertainty.'
methods='Only adld3p (4,296 missing; 74.9%) and urin1 (3,028 missing; 52.8%) were removed. cat2 remains, including its original missing-value encoding (4,535 missing; 79.1%). Original versus reduced specifications use 53 versus 51 raw adjustment variables and 72 versus 70 encoded terms. Both use the same exclusions, first-category dummy coding with no missing category, numeric median filling followed by zero fallback, standardization, and L2 logistic propensity regression (C=1, lbfgs, max_iter=5000). No missingness indicators, interactions, new exclusions or outcome models were added. Each propensity model was fitted once; its scores were clipped to [c, 1−c] for each c. Stabilized inverse-probability weights use the observed exposure prevalence and weighted risks are normalized within exposure groups. Clipping changes scores, not cohort membership. RD is RHC risk minus No RHC risk; RR is RHC risk divided by No RHC risk.'
reused='Retrieved the four analysis-stage MemoryStore records scope, timing, profile and source before estimation. Their source files guided inspection of the contract, original functions, saved estimates, workflow gates, MCP profile and PMID 8782638 literature artifact. The original pure design/fit/calc functions were extracted from analysis.py without executing its top-level analysis. Input CSV, dictionary, legacy script and contract reproduce the saved composite fingerprint. All non-database entries in the initial artifact manifest were checked against their hashes. MCP artifacts remain exploratory/unreviewed; the original CSV staging metadata explicitly says its host-supplied source reference was not independently verified. No unchanged source was refetched, and no new MCP tool call was needed.'
rerun='Actually rerun: SHA-256 checks and MemoryStore retrieval; unique-patient and exposure/outcome label checks; relevant missingness counts against the saved MCP profile; two full preprocessing/propensity fits; six clipping/weight/risk calculations; effective sample size, extreme-weight and all-original-term balance checks; original point-estimate comparison (agreement within 1e-10); controller transitions for a new bounded sensitivity run; figure generation and visual inspection. No bootstrap, multiple imputation, crude analysis, conditional outcome model, literature discovery or causal identification analysis was rerun.'
gates='The original stopped causal workflow is preserved: within-day treatment/covariate chronology, eligibility/time-zero and grace-period alignment remain unresolved. Missing-data mechanisms, structural cat2 blanks, clinical sentinel values, an adequate causal adjustment set and exchangeability remain unestablished. Deletion can increase residual confounding and does not resolve these questions. The imputed-variable balance checks do not assess unobserved values or prove exchangeability. Site-aware uncertainty and uncertainty in the change between models are unassessed. Next work requires timing/clinical adjudication, a defensible DAG, a justified missing-data and MNAR plan, and appropriate uncertainty estimation. Independent review remains pending; this is an analyst self-audit. No user scientific approval or causal readiness is implied.'
provenance=f"CSV SHA-256: {r['input_sha256']}. Composite input/contract fingerprint: {r['input_fingerprint']}. The first memory lookup used the raw CSV hash and returned four unavailable-key issues; reconstruction of the original composite fingerprint resolved them. The successful retrieval selected four keys with {log['context_utf8_bytes']:,} UTF-8 context bytes, not model tokens, and no missing/stale/conflicting or omitted keys. Both attempts are retained in followup_memory_retrieval.json. The new sensitivity decision is attributed to the Codex analyst, with the user request as scope authorization only; see followup_memory_append.json. Its dependencies reference all four prior records. Existing records were not superseded. context_sources.json identifies files, record IDs and supporting checks."
heads=['Clip','Original RD (pp)','Reduced RD (pp)','Δ RD (pp)','Original RR','Reduced RR','Δ RR']
comparison=[]
for delta in r['reduced_minus_original']:
 c=delta['clip'];a=next(x for x in r['estimates'] if x['clip']==c and x['specification']=='original');b=next(x for x in r['estimates'] if x['clip']==c and x['specification']=='reduced')
 comparison.append([f'{c:.2f}',f"{100*a['rd']:.3f}",f"{100*b['rd']:.3f}",f"+{delta['rd_change_percentage_points']:.3f}",f"{a['rr']:.4f}",f"{b['rr']:.4f}",f"+{delta['rr_change']:.4f}"])
diagheads=['Specification','Clip','RHC risk (%)','No RHC risk (%)','Clipped n','Max weight','ESS RHC / No RHC','Max |SMD|']
diag=[]
for e in r['estimates']:diag.append([e['specification'],f"{e['clip']:.2f}",f"{100*e['risk_rhc']:.3f}",f"{100*e['risk_no_rhc']:.3f}",str(e['clipped_n']),f"{e['max_weight']:.2f}",f"{e['ess']['1']:.1f} / {e['ess']['0']:.1f}",f"{e['max_abs_smd_all_original_terms']:.3f}"])
diagtext='Original versus reduced propensity fits converged without warnings. Balance is assessed on the same 72 original encoded/imputed terms using fixed unweighted pooled standard deviations. At clip 0.02, adld3p |SMD| rises from 0.039 to 0.166 and urin1 from 0.038 to 0.085. The reduced model leaves one original term above 0.10 at every threshold; the original leaves none. Full term-level diagnostics are in followup_balance.csv. Stronger clipping reduces the maximum weight but also changes the estimated association; none of these thresholds is selected as causally preferred.'
def mdtable(h,rows):return '| '+' | '.join(h)+' |\n| '+' | '.join(['---']*len(h))+' |\n'+'\n'.join('| '+' | '.join(row)+' |' for row in rows)
def htable(h,rows):return '<div class="scroll"><table><thead><tr>'+''.join('<th>'+html.escape(x)+'</th>' for x in h)+'</tr></thead><tbody>'+''.join('<tr>'+''.join('<td>'+html.escape(x)+'</td>' for x in row)+'</tr>' for row in rows)+'</tbody></table></div>'
sections=[('Adjustment and estimation',methods),('Diagnostics',diagtext),('Saved context reused',reused),('Operations rerun',rerun),('Unresolved gates and uncertainty',gates),('Provenance and memory audit',provenance)]
md='# RHC follow-up: omit adld3p and urin1\n\n'+summary+'\n\n'+warning+'\n\n'+mdtable(heads,comparison)+'\n\n![Annotated risk-difference and risk-ratio comparison](followup_figures/adjustment_comparison.png)\n\n'+mdtable(diagheads,diag)+'\n\n'
for title,body in sections:md+='## '+title+'\n\n'+body+'\n\n'
md+='## Reproduction and preserved outputs\n\nRun `PYTHONPATH=/Users/amiee/Projects_code/biostat-superpowers /tmp/biostat-rhc-analysis-env/bin/python -B followup_analysis.py`, then `/tmp/biostat-rhc-analysis-env/bin/python -B build_followup_report.py`. No dependencies were installed. Initial report.html, results.json and all original figures retain their original hashes. The new HTML embeds its figure and styles for offline viewing. Figure visually inspected; HTML source checked, but no browser rendering test performed. Software versions and complete adjustment lists are in followup_results.json.\n'
Path('FOLLOWUP.md').write_text(md)
encoded=base64.b64encode(Path('followup_figures/adjustment_comparison.png').read_bytes()).decode()
body='<h1>RHC follow-up: omit adld3p and urin1</h1><p>'+summary+'</p><p class="notice">'+warning+'</p>'+htable(heads,comparison)+'<img alt="Point estimates on annotated risk-difference and risk-ratio scales; nulls at zero and one" src="data:image/png;base64,'+encoded+'">'+htable(diagheads,diag)
for title,text in sections:body+='<h2>'+title+'</h2><p>'+html.escape(text)+'</p>'
body+='<h2>Reproduction and preservation</h2><p>'+html.escape(md.split('## Reproduction and preserved outputs\n\n')[1])+'</p>'
Path('followup.html').write_text('<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>RHC adjustment sensitivity</title><style>body{max-width:1100px;margin:40px auto;padding:0 24px;font:17px/1.6 system-ui,sans-serif;color:#183344;background:#fff}h1{line-height:1.2}h2{margin-top:32px}p{overflow-wrap:anywhere}.notice{padding:18px;background:#fff0dc;border-left:5px solid #b95d20}img{width:100%;height:auto}table{width:100%;border-collapse:collapse;font-size:14px}th,td{padding:10px;text-align:right;border-bottom:1px solid #dbe3e7}th{background:#e5eef1}.scroll{overflow:auto}</style><main>'+body+'</main></html>')
ctx=json.loads(Path('context_sources.json').read_text());assert all(hashlib.sha256(Path(p).read_bytes()).hexdigest()==h for p,h in ctx['protected_outputs_before_after'].items())
assert 'src="http' not in Path('followup.html').read_text() and '<script' not in Path('followup.html').read_text()
assert len(r['estimates'])==6 and all(e['rd_ci'] is None and e['rr_ci'] is None and e['n']==5735 for e in r['estimates'])
c=sqlite3.connect('file:project-memory.sqlite3?mode=ro',uri=True);integrity=c.execute('pragma integrity_check').fetchone()[0];c.close();assert integrity=='ok'
validation={'six_estimates':True,'all_patients_retained':True,'original_estimates_reproduced':True,'initial_outputs_unchanged':True,'csv_and_composite_fingerprint_match':True,'memory_final_issues':[],'sqlite_integrity':integrity,'figure_inspection':'PNG displayed and inspected; labels legible, nulls and scales annotated; no intervals drawn','html_check':'embedded PNG, inline CSS, no scripts or remote assets; not browser-render tested','independent_review':'pending','causal_ready':False}
Path('followup_validation.json').write_text(json.dumps(validation,indent=2))
print(json.dumps({'comparison':comparison,'validation':validation},indent=2))
