"""Build portable report from local aggregate results and native MCP snapshots."""
from pathlib import Path
import json,hashlib,html,base64
import pandas as pd
E=html.escape
R=json.loads(Path('results.json').read_text());C=json.loads(Path('analysis_config.json').read_text());N=R['cohort']['common_cases']
records=[];annotations={};targets={};literature={}
for p in Path('mcp_artifacts').glob('*/manifest.json'):
 m=json.loads(p.read_text())
 for name,v in m.get('files',{}).items():assert hashlib.sha256((p.parent/name).read_bytes()).hexdigest()==v['sha256'],str(p/name)
 records.append({'manifest':str(p),**m})
 if m.get('provider')=='UniProt':
  d=json.loads((p.parent/'summary.json').read_text())
  for a in (d if isinstance(d,list) else d.get('records',[])):annotations[a['query_symbol']]=a
 if m.get('provider')=='Open Targets':
  d=json.loads((p.parent/'response.json').read_text());t=d['data']['target'];targets[t['approvedSymbol']]=t
 if (p.parent/'literature.json').exists():
  for a in json.loads((p.parent/'literature.json').read_text())['records']:literature[a['id']]=a
Path('source_index.json').write_text(json.dumps(records,indent=2))
curated={
 'CA9':{'priority':'Strong tissue-contrast research candidate; separate imaging/biology from therapy.','independent':'ARISER: 864 randomized patients; no significant DFS advantage (HR 0.97, 95% CI 0.79–1.18) or OS advantage (HR 0.99, 0.74–1.32) for adjuvant girentuximab. This independent trial limits therapeutic extrapolation; it does not negate differential expression.','pmids':['27787547']},
 'NNMT':{'priority':'Prioritize metabolic biology and orthogonal tissue validation.','independent':'Kim et al. 2025: a separate 14-patient paired RNA study reported NNMT upregulation, with knockdown experiments in SNU1272/Caki-1 cells. TCGA survival analysis is a separate secondary component. This supports biological follow-up, not validated prognosis or human efficacy. Wang et al. 2026 report NNMT/FN1 experiments and clinical specimens; independence of their reused multiomics data from CPTAC is not established from the abstract.','pmids':['41399267','42440812']},
 'VEGFA':{'priority':'RNA upregulation; protein is untestable (only one finite pair), so protein prioritization is unsupported here.','independent':'No independent VEGFA-specific outcome study retrieved in this bounded search. Live pathway/target annotations support context only.','pmids':[]},
 'MTOR':{'priority':'Pathway-context comparator; total abundance is not kinase activity.','independent':'No independent MTOR-specific outcome study retrieved in this bounded search. Protein abundance alone cannot establish pathway activation or drug sensitivity.','pmids':[]}}
for g in R['data_driven_candidates']:curated[g]={'priority':'Exploratory large protein contrast; validate independently before target prioritization.','independent':'No candidate-specific independent literature retrieved in bounded search; annotation is not validation.','pmids':[]}
curated['NDUFA4L2']['priority']='Large concordant upward contrast; current UniProt symbol is COXFA4L2 (legacy matrix symbol NDUFA4L2), accession Q9NRX3. No Reactome pathways returned; this is not evidence of no pathway membership.'
curated['MT1H']['priority']='Large concordant downward contrast; metal-binding annotation supports a tissue-biology hypothesis, not therapeutic targeting.'
evidence=[]
for g in C['prespecified']+R['data_driven_candidates']:
 a=annotations.get(g,{});t=targets.get(g,{})
 evidence.append({'gene':g,'selection':'prespecified' if g in C['prespecified'] else 'data-driven','annotation':a,'target_evidence':t or None,**curated[g]})
Path('evidence_records.json').write_text(json.dumps({'targets':evidence,'literature':list(literature.values()),'original_study':{'pmid':'31675502','role':'source cohort, not independent evidence'},'source_index':'source_index.json','scope':'2 bounded literature searches, first page only; abstracts reviewed, no systematic review; 3 target queries; live UniProt shortlist annotations'},indent=2))
def fmt(x):return '—' if x is None or pd.isna(x) else f'{x:.3g}'
def rowtext(s):return f"{s['gene']} ({s['layer']}): n={s['n']}, Δ={fmt(s['mean_difference'])}, 95% CI [{fmt(s['ci_low'])}, {fmt(s['ci_high'])}], q={fmt(s['q_value'])}"
short=pd.DataFrame(R['shortlist'])
headline=f"{N} matched ccRCC cases; {R['assays']['protein']['q_below_005']:,} proteins at BH q < 0.05 ({R['assays']['protein']['up']:,} higher, {R['assays']['protein']['down']:,} lower in tumor)."
con=R['concordance'];agreement=f"Among {con['both_tested']:,} genes tested in both layers, {con['fraction']:.1%} have the same estimated direction (descriptive Spearman ρ={con['spearman_descriptive']:.3f}). Restricting each gene to the exact same finite cases in all four matrices gives {con['same_finite_direction_fraction']:.1%} agreement across {con['same_finite_case_genes']:,} genes."
keyfindings='CA9 and NNMT are higher in tumor in both layers; MTOR total abundance is lower in both, without establishing reduced pathway activity. VEGFA RNA is higher, but its protein has only one finite pair and is not testable. NDUFA4L2 (current UniProt COXFA4L2) is higher and MT1H lower in both layers; these were selected exploratorily.'
methods=f"Primary analysis uses the intersection of four assay case sets after excluding seven non-ccRCC cases by authoritative histology and the contaminated C3N-00314 normal specimen. Its tumor remains eligible in the inventory. {N} common cases contribute; each gene uses only its finite tumor/normal pairs. No extra log transformation or imputation. For n ≥ 20, Δ is the arithmetic mean of paired differences, SE = SD(d)/√n, nominal 95% CI = Δ ± t(0.975,n−1)×SE, and a two-sided paired t test addresses mean difference zero. BH correction uses all successfully tested genes separately within protein and RNA. Genes with fewer than 20 pairs, zero paired variance, or nonfinite failures have no p/q/CI and explicit status; descriptive means remain available. Nominal CIs are not simultaneous or adjusted for shortlist selection."
limitations="Missingness may depend on abundance and tissue (MNAR); the observed-pair mean need not represent unobserved values or all eligible cases. Common-assay selection further limits generalizability. Independent cases and sufficiently regular paired-difference means underpin t inference; pairing controls stable case characteristics but does not remove tissue composition, purity, processing or batch artifacts. TMT reference ratios can be compressed and are not directly calibrated to RNA log2 FPKM. No raw processing reconstruction or batch-adjusted model was performed. Adjacent tissue is not healthy-donor tissue. Gene dependence limits generic BH guarantees. Differences in significance do not test differences between RNA/protein effects; no cross-layer effect-equality test was performed. Direction discordance can reflect missingness, composition, processing and post-transcriptional regulation; it does not establish a mechanism. No enrichment test, causal claim, drug efficacy claim or clinical recommendation is made."
md=['# CPTAC ccRCC paired RNA/protein exploratory report','',headline,'',keyfindings,'',agreement,'','## Cohort and method','',methods,'',f"Download: 110 tumors, 84 protein normals, 75 RNA normals. After exclusions: {R['cohort']['layer_pairs']['protein']} protein pairs and {R['cohort']['layer_pairs']['rna']} RNA pairs; primary common cohort {N}. All nine file hashes/sizes verified against input/manifest.json. The workbook contamination note and specimen mapping were checked.",'','## Shortlist','',C['selection'],'','| Gene | Layer | n | Mean Δ | 95% CI | p | BH q | Status |','|---|---|---:|---:|---|---:|---:|---|']
for s in R['shortlist']:md.append(f"| {s['gene']} | {s['layer']} | {s['n']} | {fmt(s['mean_difference'])} | {fmt(s['ci_low'])}, {fmt(s['ci_high'])} | {fmt(s['p_value'])} | {fmt(s['q_value'])} | {s['status']} |")
md+=['','Protein Δ is on processed TMT log2 reference-ratio scale; RNA Δ is on supplied log2 FPKM scale.','', '## Research evidence','']
for ev in evidence:
 md += [f"**{ev['gene']}** — {ev['priority']} {ev['independent']}"]
 for pmid in ev['pmids']:md += [f"[{literature[pmid]['title']}](https://pubmed.ncbi.nlm.nih.gov/{pmid}/) (PMID {pmid})."]
md+=['','Live UniProt identifiers/pathways and Open Targets records for CA9, VEGFA and MTOR are in evidence_records.json. Open Targets returns all-indication records (first 10); CA9 includes girentuximab and an iodine-124 imaging agent, VEGFA includes bevacizumab, and MTOR includes multiple investigational kinase inhibitors. Database stage labels are not jurisdiction/indication-specific approval statements. NNMT and the two exploratory candidates were not queried for drug records. Reactome annotations are not enrichment evidence.','','## Limitations and follow-up','',limitations,'','Independent evaluation is pending, with the controller blocked at evaluation. Same-session numerical and artifact checks do not confer scientific approval. Next: independent code/results review, investigate batch/purity and missingness, verify candidate expression orthogonally, and review full texts before translating prioritization.','','Reproduce offline: `/tmp/biostat-rhc-analysis-env/bin/python analysis.py` then `/tmp/biostat-rhc-analysis-env/bin/python render_report.py`. Runtime code path is recorded in analysis.py. Read runtime_context.json and memory_retrieval.json before follow-up. Full aggregate tables are under tables/; raw evidence, dates, queries, URLs and checksums are under mcp_artifacts/ and source_index.json.']
discord=pd.read_csv('tables/discordant_examples.csv') if Path('tables/discordant_examples.csv').exists() else pd.DataFrame()
if len(discord): md += ['', 'Examples with opposite directions and q < 0.05 in both layers (exploratory; not tests of layer-effect differences): '+', '.join(discord.gene)+'. Full estimates: tables/discordant_examples.csv.']
Path('report.md').write_text('\n'.join(md)+'\n')
def image(name,alt):return '<img alt="'+E(alt)+'" src="data:image/png;base64,'+base64.b64encode(Path('figures/'+name+'.png').read_bytes()).decode()+'">'
rows=''
for ev in evidence:
 a=ev['annotation'];matches=a.get('matches',[]);mapping='; '.join(m['accession']+' / '+', '.join(m['ensembl_gene_ids']) for m in matches) or 'Unavailable';paths='; '.join(p['name'] for m in matches for p in m.get('reactome_pathways',[])) or 'No returned pathways'
 t=ev['target_evidence'];drugs='Not queried (bounded scope)';tract='Not queried'
 if t:
  dd=t['drugAndClinicalCandidates'];drugs=f"{len(dd['rows'])} of {dd['count']} records: "+'; '.join(x['drug']['name']+' ('+x['maxClinicalStage']+')' for x in dd['rows']);tract='; '.join(x['modality']+': '+x['label'] for x in t['tractability'] if x['value'])
 links=' '.join('<a href="https://pubmed.ncbi.nlm.nih.gov/'+p+'/">PMID '+p+'</a>' for p in ev['pmids'])
 rows+='<tr><th>'+E(ev['gene'])+'<small>'+E(ev['selection'])+'</small></th><td>'+E(mapping)+'<details><summary>Pathway annotations</summary>'+E(paths)+'</details></td><td>'+E(ev['priority'])+'<p>'+E(ev['independent'])+'</p>'+links+'</td><td><details><summary>Tractability and drug records</summary>'+E(tract)+'<p>'+E(drugs)+'</p></details></td></tr>'
allrows=[]
for layer in ['protein','rna']:
 d=pd.read_csv('tables/'+layer+'_all_genes.csv');d['layer']=layer;allrows += [{k:(None if pd.isna(v) else v) for k,v in row.items()} for row in d.to_dict(orient='records')]
jsdata=json.dumps(allrows,separators=(',',':')).replace('</','<\\/')
page='''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>CPTAC ccRCC | paired molecular atlas</title><style>
:root{color-scheme:light;--ink:#132c40;--blue:#006ca5;--muted:#526777}*{box-sizing:border-box}body{margin:0;background:#f3f6fa;color:var(--ink);font:16px/1.6 system-ui,sans-serif}header{background:#112f44;color:white;padding:48px max(5vw,24px)}header p{max-width:960px;color:#d2e4ee}.eyebrow{letter-spacing:.15em;text-transform:uppercase;font-size:12px;color:#82d6ed}h1{font-size:clamp(30px,4vw,50px);line-height:1.15;margin:14px 0}h2{line-height:1.25}main{max-width:1250px;margin:auto;padding:20px}.cards{display:grid;grid-template-columns:repeat(3,1fr);gap:16px}.card,section{background:white;border:1px solid #dfe7ed;border-radius:12px;padding:25px;margin-bottom:20px}.card strong{font-size:32px;display:block;color:var(--blue)}nav{padding:12px 0;display:flex;gap:20px;flex-wrap:wrap}a{color:#006ca5}header a{color:#a9e3fa}img{width:100%;height:auto}.grid{display:grid;grid-template-columns:1fr 1fr;gap:20px}.notice{border-left:5px solid #d17900;background:#fff8e9;padding:15px}table{border-collapse:collapse;width:100%;font-size:13px}th,td{text-align:left;padding:10px;border-bottom:1px solid #dfe7ed;vertical-align:top}th{background:#edf4f8}small{display:block;color:var(--muted)}.scroll{overflow:auto;max-height:600px}label{display:inline-block;margin:0 20px 12px 0}input,select,button{font:inherit;border:1px solid #8da1b2;border-radius:5px;padding:6px}button{cursor:pointer;background:#e6f2f9}summary{cursor:pointer;color:#006ca5}footer{padding:25px;color:var(--muted)}@media(max-width:760px){.cards,.grid{grid-template-columns:1fr}section{padding:16px}}
</style><header><div class="eyebrow">CPTAC · clear-cell renal cell carcinoma</div><h1>Paired tissues, two molecular layers</h1><p>Exploratory associations and research prioritization. Offline report • independent review pending.</p><nav><a href="#cohort">Cohort</a><a href="#effects">Protein differences</a><a href="#concordance">RNA / protein</a><a href="#evidence">Evidence matrix</a><a href="#explore">Gene explorer</a><a href="#limits">Limits & provenance</a></nav></header><main>'''
page+=f'<div class="cards"><div class="card"><strong>{N}</strong>matched common cases</div><div class="card"><strong>{R["assays"]["protein"]["q_below_005"]:,}</strong>proteins with BH q &lt; 0.05</div><div class="card"><strong>{con["fraction"]:.1%}</strong>same estimated RNA / protein direction</div></div>'
page+='<section id="cohort"><h2>A common cohort, preserved pairing</h2><p>'+E(methods)+'</p>'+image('availability_missingness','Downloaded and eligible sample availability and gene-wise finite pair counts')+'<details><summary>Audit details and testing families</summary><pre>'+E(json.dumps({'cohort':R['cohort'],'assays':R['assays']},indent=2))+'</pre></details></section>'
page+='<section id="effects"><h2>Protein differences and shortlist uncertainty</h2><p>'+E(headline)+'</p><p>'+E(keyfindings)+'</p>'+image('protein_differential','Protein paired mean differences versus BH q values')+'<p>'+E(C['selection'])+'</p>'+image('shortlist_intervals','Separate RNA and protein shortlist estimates with nominal 95 percent confidence intervals')+short[['gene','layer','n','mean_difference','ci_low','ci_high','p_value','q_value','status']].to_html(index=False,float_format=lambda x:f'{x:.3g}',border=0)+'</section>'
page+='<section id="concordance"><h2>Agreement of directions, not equality of scales</h2><p>'+E(agreement)+'</p>'+image('concordance','RNA and protein mean difference density with separate supplied scale labels')+'<p class="notice">Significance in one layer and not the other is not evidence that layer effects differ. No diagonal equality line or effect subtraction is used because the scales are not interchangeable.</p></section>'
if len(discord): page+='<section><h2>Opposite-direction examples</h2><p>Exploratory genes with q &lt; 0.05 in both layers, ranked by absolute protein difference. This is not a test of cross-layer effect differences.</p>'+discord[['gene','n_protein','mean_difference_protein','ci_low_protein','ci_high_protein','n_rna','mean_difference_rna','ci_low_rna','ci_high_rna']].to_html(index=False,float_format=lambda x:f'{x:.3g}',border=0)+'</section>'
page+='<section id="evidence"><h2>Target–evidence matrix</h2><p>UniProt: reviewed human entries, mappings and Reactome annotations. No enrichment claim. Open Targets: all-indication tractability and up to 10 drug records per target, not kidney-specific efficacy. SM = small molecule; AB = antibody; PR = proteolysis; OC = other modality.</p><div class="scroll"><table><thead><tr><th>Gene / selection</th><th>Identifier / annotation</th><th>Research interpretation / independent evidence</th><th>All-indication target records</th></tr></thead><tbody>'+rows+'</tbody></table></div><p>Original Clark et al. 2019 (PMID 31675502) supplies this cohort and is not independent validation. Literature search was bounded to two queries and five returned records, with abstracts reviewed. A missing search hit is not evidence of absence.</p></section>'
page+='''<section id="explore"><h2>Explore every aggregate gene result</h2><label>Gene <input id="search" placeholder="e.g. CA9" aria-label="Gene search"></label><label>Layer <select id="layer"><option value="protein">Protein</option><option value="rna">RNA</option></select></label><label><input id="sig" type="checkbox"> BH q &lt; 0.05 only</label><label>Sort <select id="sort"><option value="q_value">BH q ascending</option><option value="mean_difference">Absolute mean difference</option><option value="gene">Gene A–Z</option></select></label><button id="export">Download filtered CSV</button><p id="count" aria-live="polite"></p><div class="scroll"><table><thead><tr><th>Gene</th><th>n</th><th>Mean Δ</th><th>95% CI</th><th>p</th><th>BH q</th><th>Status</th></tr></thead><tbody id="body"></tbody></table></div><p>Display capped at 200 rows; CSV export includes every filtered row. Full static CSVs: <a href="tables/protein_all_genes.csv">protein</a> · <a href="tables/rna_all_genes.csv">RNA</a>.</p></section>'''
page+='<section id="limits"><h2>Limits, diagnostics and provenance</h2><p>'+E(limitations)+'</p><details><summary>Shortlist influence diagnostics</summary><p>Leave-one-case-out ranges and medians assess whether a single case determines the estimated direction. They do not validate missing-data or batch assumptions.</p>'+pd.DataFrame(json.loads(Path('diagnostics.json').read_text())).to_html(index=False,float_format=lambda x:f'{x:.3g}',border=0)+'</details><p class="notice">Independent evaluation is pending. Controller analysis gate is complete; evaluation is blocked. This draft report is an artifact for review, not a ready scientific handoff.</p><p><a href="report.md">Concise Markdown</a> · <a href="results.json">Results JSON</a> · <a href="analysis_config.json">Configuration</a> · <a href="source_index.json">Source URLs, dates and hashes</a> · <a href="evidence_records.json">Evidence records</a> · <a href="runtime_context.json">Follow-up context</a> · <a href="analysis.py">Analysis code</a></p><p>All input hashes/sizes verified. Public processed host-supplied matrices; live evidence obtained through native MCP. No sequencing, mass-spectrometry raw data, or additional cohort data downloaded. Sources retrieved 2026-09-24. Full source responses and manifests remain local in mcp_artifacts/.</p></section></main><footer>STROBE-informed exploratory tissue analysis • no remote scripts, fonts or CDNs • figures and aggregate data embedded</footer>'
page+='<script>const data='+jsdata+r''';let selected=[];const el=id=>document.getElementById(id);const fmt=v=>v==null?'—':Number(v).toPrecision(4);function draw(){selected=data.filter(r=>r.layer===el('layer').value&&r.gene.toLowerCase().includes(el('search').value.toLowerCase())&&(!el('sig').checked||(r.q_value!=null&&r.q_value<.05)));let s=el('sort').value;selected.sort((a,b)=>s==='gene'?a.gene.localeCompare(b.gene):s==='mean_difference'?Math.abs(b[s]||0)-Math.abs(a[s]||0):(a[s]??Infinity)-(b[s]??Infinity));el('count').textContent=selected.length+' matching genes; showing first '+Math.min(200,selected.length);el('body').replaceChildren();for(const r of selected.slice(0,200)){let tr=document.createElement('tr');for(const x of [r.gene,r.n,fmt(r.mean_difference),fmt(r.ci_low)+' to '+fmt(r.ci_high),fmt(r.p_value),fmt(r.q_value),r.status]){let td=document.createElement('td');td.textContent=x;tr.append(td)}el('body').append(tr)}}for(const id of ['search','layer','sig','sort'])el(id).addEventListener('input',draw);el('export').onclick=()=>{let keys=['gene','layer','n','mean_difference','ci_low','ci_high','p_value','q_value','status'];let csv=[keys.join(','),...selected.map(r=>keys.map(k=>JSON.stringify(r[k]??'')).join(','))].join('\n');let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='filtered_gene_results.csv';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};draw();</script></html>'''
Path('report.html').write_text(page)
print('Built report.html, report.md, evidence_records.json and source_index.json; annotations:',list(annotations))
