"""Build an offline comparison page from aggregate collected artifacts."""
import json,html,sys
from pathlib import Path
r=Path(sys.argv[1]);rows=json.loads((r/'telemetry.json').read_text())
table=''
for row in rows:
 u=row['usage'] or {};table+=f"<tr><td>{row['arm'].title()}</td><td>{row['phase'].title()}</td>"+''.join(f'<td>{u.get(k,0):,}</td>' for k in ['input_tokens','cached_input_tokens','uncached_input_tokens','output_tokens'])+f"<td>{row['seconds']/60:.1f} min</td></tr>"
panels=''
for name,label in [('flow','Cohort'),('missingness','Missingness'),('diagnostics','Balance & overlap'),('sensitivity','Sensitivity')]:
 panels+=f'<section><h2>{label}</h2><div class="pair">'
 for arm in ['baseline','upgraded']:
  panels+=f'<figure><figcaption>{arm.title()}</figcaption><a href="{arm}/figures/{name}.png"><img src="{arm}/figures/{name}.png" alt="{arm} {label}"></a></figure>'
 panels+='</div></section>'
follow=''
for arm in ['baseline','upgraded']:
 follow+=f'<a class="button" href="{arm}/followup.html">{arm.title()} follow-up report →</a> '
page='''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>RHC · What did the new workflow add?</title><style>
*{box-sizing:border-box}body{margin:0;background:#f4f6fa;color:#172b3b;font:17px/1.6 system-ui,sans-serif}main{max-width:1380px;margin:auto;padding:42px 28px}h1{font-size:clamp(30px,4vw,52px);line-height:1.13;max-width:950px}h2{font-size:26px}header p{max-width:900px}.eyebrow{color:#006c78;letter-spacing:.12em;font-weight:700;font-size:13px}.cards,.pair{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:24px}.card,section{background:white;border:1px solid #dce3e9;border-radius:16px;padding:24px;margin:24px 0}.card{margin:0}.card b{font-size:22px;display:block}a{color:#056b83}a.button{display:inline-block;background:#163b50;color:white;text-decoration:none;padding:10px 15px;border-radius:8px;margin:8px 8px 8px 0}figure{margin:0;min-width:0}figcaption{font-weight:700;margin:8px 0}img{width:100%;height:auto;border:1px solid #edf0f5}table{border-collapse:collapse;width:100%;font-size:14px}th,td{text-align:right;padding:12px;border-bottom:1px solid #dce3e9}th:first-child,td:first-child{text-align:left}.scroll{overflow:auto}.note{border-left:4px solid #af5c20;padding-left:16px}.muted{color:#546777;font-size:15px}@media(max-width:800px){.pair,.cards{grid-template-columns:1fr}main{padding:24px 16px}}
</style><main><header><div class="eyebrow">RIGHT-HEART CATHETERIZATION · MATCHED AGENT PILOT · SEPTEMBER 2026</div><h1>What did the new workflow actually add?</h1><p>Two fresh agents received the same 5,735-patient dataset, research request and model. One used the original statistical skills; the other added an executable controller, project memory and MCP. Each then resumed in a fresh session for the same sensitivity question.</p><p class="note">This is one pilot, not a causal experiment proving component benefits. Jev was excluded. Both analyses remain exploratory and do not establish that RHC causes harm.</p></header>
<div class="cards"><div class="card"><b>Similar scientific and visual quality</b><p>Independent review: baseline 81.7/100; upgraded 83.3/100. A small subjective score difference is not evidence of superiority. Both produced five useful analytical figures.</p><a href="independent_review.md">Read the independent review</a></div><div class="card"><b>More explicit provenance and recorded stops</b><p>The upgraded run used actual MCP import, profiling, literature retrieval and chart rendering. It persisted and retrieved four scoped decisions. These additions have overhead; token savings must be measured.</p><a href="mcp_calls.json">Actual MCP calls</a> · <a href="upgraded/workflow-transitions.json">Workflow evidence</a></div></div>
<section><h2>Explore both reports</h2><p>The full reports contain effect estimates, uncertainty methods, limitations and interactive views. Figures below can be opened at full resolution.</p><a class="button" href="baseline/report.html">Original-skills report →</a><a class="button" href="upgraded/report.html">Upgraded report →</a>'''+follow+'''<p><strong>Trade-offs:</strong> the baseline flagged 11 no-death records with last contact before day 30. The upgraded report added balance checks for missingness indicators and source provenance. Neither removes the need for scientific review.</p></section>
<section><h2>Measured model usage</h2><p>Input counts include repeated context across calls; cached input is a subset, not an extra charge. Uncached input is input minus cached input. Output includes reasoning tokens where reported; do not add reasoning again. These are host telemetry counts, not billed dollar amounts.</p><div class="scroll"><table><thead><tr><th>Configuration</th><th>Phase</th><th>Total input</th><th>Cached input</th><th>Uncached input</th><th>Output</th><th>Elapsed</th></tr></thead><tbody>'''+table+'''</tbody></table></div><p><strong>Observed result: the upgraded workflow used 48.3% more uncached input and 29.3% more output across both phases. No token savings were demonstrated.</strong></p><p>Both configurations could reuse ordinary saved files; the baseline was not forced to replay a conversation. Differences include tool-schema/API-learning overhead and stochastic agent choices, so this cannot isolate memory's effect.</p><a href="README.md">Interpretation and limitations</a> · <a href="telemetry.json">Machine-readable telemetry</a></section>'''+panels+'''<section><h2>What MCP contributed to visualization</h2><p>The extra age histogram below was rendered by the MCP server from its checksummed data/profile artifacts. The five main statistical figures were generated with scientific Python in both configurations. A gallery connection is useful infrastructure, but it does not automatically produce better statistical figures.</p><img style="max-width:750px" src="upgraded/figures/mcp_age_histogram.png" alt="MCP-rendered age distribution"><p class="muted">Public RHC data courtesy Vanderbilt Biostatistics. Source details and checksums are recorded in the study protocol. Frozen initial artifacts were checked for preservation after follow-up.</p></section></main></html>'''
(r/'index.html').write_text(page)
