import json,html,base64,re,hashlib
from pathlib import Path
import pandas as pd,numpy as np
P=Path(__file__).resolve().parent;O=P/'outputs';S=P/'sources'
r=json.loads((P/'results.json').read_text());cfg=json.loads((P/'analysis_config.json').read_text());a=json.loads((S/'annotations.json').read_text());short=pd.read_csv(O/'shortlist.csv');esc=html.escape
# Resolve the historical matrix symbol using the explicit UniProt synonym, not row order.
u=json.loads((S/'uniprot_NDUFA4L2.json').read_text())['results'];matches=[x for x in u if any(y.get('value')=='NDUFA4L2' for g in x.get('genes',[]) for y in g.get('synonyms',[]))]
assert len(matches)==1;x=matches[0];a['NDUFA4L2']=dict(status='Unique reviewed human synonym match; historical NDUFA4L2 maps to current COXFA4L2',current_symbol='COXFA4L2',accession=x['primaryAccession'],ensembl_gene_ids=['ENSG00000185633'],protein=x['proteinDescription'],reactome=[y for y in x.get('uniProtKBCrossReferences',[]) if y['database']=='Reactome']);(S/'annotations.json').write_text(json.dumps(a,indent=2))
limitations='These are exploratory tissue associations, not causal effects, treatment-response predictions or clinical advice. Adjacent tissue is not healthy-donor kidney. Cell composition, tumor purity, clinical heterogeneity and unmodeled processing/batch effects may explain differences. Pairing controls stable case characteristics but does not remove tissue-confounded technical effects. TMT reference ratios may show ratio compression; supplied RNA normalization and original processing are accepted, not reproduced. No extra log transform was applied. Protein missingness may depend on abundance (MNAR); available-pair results need not represent all 72 cases or all ccRCC. The common-assay cohort may be selected. Many significant genes can reflect broad tissue and technical differences. No enrichment analysis was performed; pathway annotations are not enrichment evidence.'
methods='The unit is the case, with tumor and normal-adjacent tissue paired by exact case identifier. Authoritative workbook-derived histology excludes seven non-ccRCC cases. The contaminated C3N-00314 normal (CPT0012090003) is excluded; its tumor remains in availability counts. The intersection of all four assays defines 72 cases. Per gene/layer, only pairs with both values finite are used. Genes require at least 20 such pairs. Mean differences, sample SD, two-sided paired t p-values and pointwise t 95% CIs use n−1 degrees of freedom. BH correction is separate for each layer’s valid tested family. Zero-variance differences retain their mean but have undefined CI/p/q and an explicit status; no automatic p=0 or p=1 assignment. T inference assumes independent cases and approximately normal sampling of the mean; CIs are not simultaneous or selection-adjusted. No outlier deletion, imputation or predictive split is used.'
headline='72 paired ccRCC cases; 8,219 of 10,033 tested proteins have BH q < 0.05 (4,491 higher; 3,728 lower). RNA: 15,118 of 19,015 tested genes. Across 9,475 genes tested in both layers, 7,205 (76.0%) share effect direction; descriptive Spearman correlation of mean differences is 0.697.'
interpret='CA9 and NNMT show substantial increases in both layers; NDUFA4L2 (current UniProt symbol COXFA4L2) is the strongest eligible exploratory protein increase, while MT1H shows a large decrease. MTOR total abundance decreases modestly in protein and also decreases in RNA; total abundance is not kinase activity. VEGFA RNA increases, but its protein estimate has only one finite pair and is not inferentially interpretable. Different RNA/protein significance does not test a difference between their effects, and their raw scales are not interchangeable.'
interpret+=' Opposite directions occur in 2,270 jointly tested genes, including 1,087 with q < 0.05 in both layers. Illustrative, post hoc examples with all 72 pairs are SLC4A1 (protein +1.651; RNA −4.153) and GM2A (protein −1.980; RNA +1.711). These separate-scale contrasts can reflect regulation, tissue composition, or processing; they do not identify a mechanism.'
selection=cfg['selection_rule']+' CA9, NNMT, VEGFA and MTOR were prespecified by the user; NDUFA4L2 and MT1H are selected from these data and subject to winner’s curse. None of these selections has been independently validated as a tissue contrast in this analysis.'
notes={
'CA9':'Prioritize orthogonal abundance/localization work. Large concordant increase; CAIX-targeted girentuximab literature supplies independent imaging evidence, not proof of therapeutic benefit.',
'NNMT':'Prioritize metabolic and cell-type follow-up. Concordant increase and nicotinamide-related annotation. Retrieved mechanistic abstracts are supportive but their multiomics cohort overlap was not audited; do not label those components independent replication.',
'VEGFA':'RNA-supported pathway candidate only: protein is effectively unavailable (n=1). VEGF-pathway trial evidence is independent, but receptor inhibitor efficacy does not validate VEGFA abundance as a response biomarker.',
'MTOR':'Pathway benchmark rather than overexpression lead. Decreased total abundance does not establish pathway inactivity. Independent temsirolimus trial supports historical RCC pathway relevance, not efficacy inferred from these tissue values.',
'NDUFA4L2':'Exploratory abundance lead; UniProt renamed it COXFA4L2. Retrieved renal cell/model literature motivates mechanistic work; observational cohort overlap is unverified. No tractability query performed for this target.',
'MT1H':'Exploratory decrease suitable for orthogonal validation; examine metallothionein isoform specificity and cellular composition. No independent target-specific paper or tractability assessment in this bounded search.'}
selected_records=[('mtor_renal','17538086','Independent randomized trial, not CPTAC','626 poor-prognosis metastatic RCC patients; temsirolimus versus interferon reported an overall-survival HR of 0.73 (95% CI 0.58–0.92). Historical trial context, not a recommendation or an abundance-response link.'),('vegf_independent','17215529','Independent randomized trial, not CPTAC','750 untreated metastatic RCC patients; sunitinib versus interferon reported progression-free-survival HR 0.42 (95% CI 0.32–0.54). Multi-target receptor inhibition provides pathway-level context, not direct validation of VEGFA protein or a ligand-specific effect.'),('ca9_zircon','42025513','Independent of CPTAC; reanalysis of ZIRCON, not a new trial','CAIX-directed radiotracer study supports imaging/localization relevance. Reanalysis is not independent of the original ZIRCON trial; diagnostic performance is not drug efficacy.'),('nnmt_renal','42440812','Mechanistic abstract; cohort overlap unverified','Reports NNMT/FN1 experiments and clinical specimens. Functional model evidence is distinct from this association analysis; independent human tissue replication and drug selectivity were not established here.'),('ndufa4l2_renal','42331208','Mechanistic abstract; cohort overlap unverified','Reports knockdown/rescue, cell and in vivo work concerning ferroptosis. Supports research motivation; abstract-level evidence does not establish clinical benefit.')]
evidence=[]
for name,pid,typ,note in selected_records:
 d=json.loads((S/(name+'.json')).read_text()); rr=[x for x in d.get('resultList',{}).get('result',[]) if x.get('id')==pid]
 if rr:
  x=rr[0];evidence.append(dict(pmid=pid,title=x['title'],year=x.get('pubYear'),doi=x.get('doi'),url='https://pubmed.ncbi.nlm.nih.gov/'+pid+'/',evidence_type=typ,interpretation=note,source_file='sources/'+name+'.json',scope='Bibliographic record and abstract reviewed; no full-text audit'))
(S/'evidence_records.json').write_text(json.dumps(evidence,indent=2))
# Do not lose supplemental source provenance on cached reruns.
provs=[json.loads(p.read_text()) for p in S.glob('*.provenance.json')];(S/'source_manifest.json').write_text(json.dumps(sorted(provs,key=lambda x:x['name']),indent=2))
def fmt(x):return '—' if pd.isna(x) else f'{x:.3g}'
view=short[['gene','layer','n','mean_difference','ci95_low','ci95_high','p','q','status']].copy()
view.columns=['Gene','Layer','Finite pairs','Mean Δ','95% CI low','95% CI high','p','BH q','Status']
table=view.to_html(index=False,float_format=fmt,border=0,classes='data')
mat=[]
for g in r['shortlist']:
 x=a[g];paths=[z['id']+': '+next((v['value'] for v in z.get('properties',[]) if v['key']=='PathwayName'),'') for z in x.get('reactome',[])];ot=x.get('open_targets',{}).get('data',{}).get('target',{}) or {};drug=ot.get('drugAndClinicalCandidates',{});rows=drug.get('rows',[]);priority={'CA9':['GIRENTUXIMAB','IODINE I 124 GIRENTUXIMAB'],'VEGFA':['BEVACIZUMAB','AFLIBERCEPT'],'MTOR':['VISTUSERTIB','SAPANISERTIB','RIDAFOROLIMUS']}.get(g,[]);chosen=sorted(rows,key=lambda d:(d['drug']['name'] not in priority,d['drug']['name']))[:3];tract=[t['modality']+': '+t['label'] for t in ot.get('tractability',[]) if t.get('value')]
 mat.append(dict(gene=g,accession=x.get('accession'),ensembl=x.get('ensembl_gene_ids'),current_symbol=x.get('current_symbol',g),pathways=paths,tractability_positive=tract,drug_record_count=drug.get('count'),drug_examples=chosen,priority_rationale=notes[g]))
(S/'target_evidence_matrix.json').write_text(json.dumps(mat,indent=2));r['target_evidence']=mat;r['literature']=evidence;r['limitations']=limitations;r['source_manifest']='sources/source_manifest.json';(P/'results.json').write_text(json.dumps(r,indent=2,allow_nan=False))
mt='<table><thead><tr><th>Target / identifiers</th><th>Annotation</th><th>Tractability / all-indication records</th><th>Research interpretation</th></tr></thead><tbody>'
for x in mat:
 drugs='; '.join(d['drug']['name']+' ('+d['maxClinicalStage']+')' for d in x['drug_examples']);mt+='<tr><td><b>'+esc(x['gene'])+'</b><br>'+esc(str(x['current_symbol']))+'<br>'+esc(str(x['accession']))+'<br>'+esc(', '.join(x['ensembl'] or []))+'</td><td>'+esc('; '.join(x['pathways']) or 'No Reactome cross-reference returned; not evidence of no pathway')+'</td><td>'+esc('; '.join(x['tractability_positive']) or 'Not assessed in the three-target query scope')+'<hr>'+esc(drugs or 'Not assessed')+('<br>'+str(x['drug_record_count'])+' total records; up to 3 shown' if x['drug_record_count'] is not None else '')+'</td><td>'+esc(x['priority_rationale'])+'</td></tr>'
mt+='</tbody></table>'
sourcehtml=''.join('<li><a href="'+esc(e['url'])+'">'+esc(e['title'])+'</a> ('+str(e['year'])+', PMID '+e['pmid']+'). <b>'+esc(e['evidence_type'])+'</b>. '+esc(e['interpretation'])+'</li>' for e in evidence)
provhtml=''.join('<li><a href="'+esc(x['url'])+'">'+esc(x['name'])+'</a> — '+esc(x['retrieved_utc'])+'; status '+str(x['status'])+'; SHA256 <code>'+x['sha256']+'</code></li>' for x in sorted(provs,key=lambda x:x['name']))
allrows=[]
for l in ['protein','rna']:
 df=pd.read_csv(O/f'{l}_all_genes.csv');df['layer']=l;allrows+=json.loads(df[['gene','layer','n','mean_difference','ci95_low','ci95_high','p','q','status']].to_json(orient='records'))
plots=''
for name,alt in [('availability','Sample availability and eligibility'),('missingness','Finite pair counts by gene and assay'),('protein_differential','Paired protein mean difference versus adjusted significance'),('concordance','RNA and protein effect directions on separate scales')]:
 plots+='<figure><img src="data:image/png;base64,'+base64.b64encode((O/(name+'.png')).read_bytes()).decode()+'" alt="'+alt+'"><figcaption>'+alt+'. Aggregate results; no participant values.</figcaption></figure>'
checks='Protein missingness is 21.38% of tumor entries and 21.38% of normal entries across all 11,710 rows; 1,677 protein genes fail the 20-pair threshold. RNA entries are finite throughout, but 260 genes have zero-variance paired differences and are not tested. Paired protein completeness has median 72 and lower quartile 43. Complete RNA values do not imply complete biological detection. Same-finite-case cross-layer sensitivity yields 76.05% direction agreement among 9,482 genes with ≥20 joint finite pairs (includes seven constant RNA genes; denominator differs from tested-only comparison). Layer-specific protein sensitivity uses 80 pairs; shortlisted tested protein directions persist. Leave-one-pair-out means retain direction for all tested shortlist effects; bootstrap CIs and skewness diagnostics are in shortlist.csv. These checks do not solve MNAR or batch confounding.'
review=dict(readiness='Usable for bounded exploratory association with stated limitations; independent review pending',review_type='Same-agent artifact and numerical checks; not independent scientific approval',strengths=['Pairing retained','Fingerprint assertions','Separate BH families','Explicit zero-variance and missingness status','Independent trial records separated from cohort evidence'],limitations=[dict(severity='serious',issue='Abundance-dependent protein missingness and common-cohort selection',action='Orthogonal assay validation; MNAR sensitivity if defensible detection assumptions become available'),dict(severity='serious',issue='Processed scales and tissue/batch confounding not audited from raw data',action='Obtain detailed processing/batch design before stronger biological claims'),dict(severity='routine',issue='Shortlist selected on observed effects',action='Validate in independent specimens; no selection-adjusted intervals claimed'),dict(severity='routine',issue='Bibliographic abstract-level evidence and database stages',action='Review full text and indication-specific records before translational prioritization')])
(P/'method_review.json').write_text(json.dumps(review,indent=2))
md='# Paired CPTAC ccRCC exploratory analysis\n\n'+headline+'\n\n'+interpret+'\n\n## Cohort and methods\n\n'+methods+'\n\nProtein: supplied processed TMT log2 reference ratios. RNA: supplied log2 FPKM. Seven histology exclusions leave 103 tumors; protein NAT 84 → 81 → 80, RNA NAT 75 → 73 → 72 after histology and contamination filters. Nine file SHA256 hashes, byte counts and combined manifest fingerprint verified.\n\n## Shortlist\n\n'+selection+'\n\n|Gene|Layer|n|Mean Δ|95% CI|BH q|\n|---|---|---:|---:|---|---:|\n'
for _,x in short.iterrows():md+=f"|{x.gene}|{x.layer}|{x.n}|{fmt(x.mean_difference)}|{fmt(x.ci95_low)} to {fmt(x.ci95_high)}|{fmt(x.q)}|\n"
md+='\nVEGFA protein has insufficient pairs; its descriptive mean is not a tested result.\n\n## Evidence and prioritization\n\n'+'\n\n'.join('**'+g+'**: '+notes[g] for g in r['shortlist'])+'\n\n'+ '\n\n'.join('['+e['title']+']('+e['url']+') — '+e['evidence_type']+'. '+e['interpretation'] for e in evidence)+'\n\nUniProt annotations obtained for all six targets; NDUFA4L2 resolved explicitly through its synonym to COXFA4L2. Open Targets assessed CA9, VEGFA and MTOR only. Stage labels and candidates span all indications and can include imaging agents or multi-target drugs; they are not jurisdiction-specific approvals or kidney efficacy. MTOR candidate rows omit temsirolimus in this snapshot; literature supplies its independent historical context. No enrichment claim. Original cohort: Clark et al., Cell 2019, PMID 31675502, is provenance rather than independent validation.\n\n## Diagnostics and limitations\n\n'+checks+'\n\n'+limitations+'\n\nTwo initial Europe PMC searches returned HTTP 503; bounded replacement queries succeeded. A guessed PMID (17476008) resolved to an unrelated cardiac trial and was rejected after title/abstract checking; raw record retained for audit. MT1H lacks target-specific independent literature in this bounded review. Full-text cohort-overlap checks, explicit MNAR modeling, batch adjustment and independent artifact review remain unresolved.\n\n## Reproduce\n\n`/tmp/biostat-rhc-analysis-env/bin/python analysis.py` then `.../python supplement_evidence.py` (uses cached original and supplemental responses), then `.../python build_report.py`. No installs. Package versions and choices are in analysis_config.json; source bytes, request URLs, retrieval dates and SHA256 are in sources/. Full aggregate tables and PNGs are in outputs/. report.html embeds plots and data and works offline. Method review is same-agent only.\n'
(P/'report.md').write_text(md)
css='body{margin:0;background:#f1f5f8;color:#152c3b;font:16px/1.55 system-ui,sans-serif}main{max-width:1200px;margin:auto;padding:30px}header{background:#12384a;color:white;padding:35px;border-radius:15px}h1{font-size:36px;line-height:1.15}section{background:white;border-radius:12px;padding:25px;margin:20px 0;overflow:auto}h2{color:#125d78}table{border-collapse:collapse;width:100%;font-size:13px}th,td{text-align:left;padding:9px;border-bottom:1px solid #dae3e8;vertical-align:top}th{background:#e8f1f5;cursor:pointer}input,select,button{padding:10px;margin:5px;border:1px solid #7997a7;border-radius:5px;background:white;color:#152c3b}figure{margin:10px}img{max-width:100%;height:auto}figcaption,.muted{color:#526771;font-size:13px}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(430px,1fr));gap:10px}a{color:#086789}code{overflow-wrap:anywhere}nav a{color:#aee8ff;margin-right:20px}.note{border-left:5px solid #d58529;padding:12px;background:#fff8ee}li{margin:10px 0}@media(max-width:600px){main{padding:10px}.grid{display:block}h1{font-size:28px}}'
page='<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>CPTAC ccRCC • Paired tissue atlas</title><style>'+css+'</style><main><header><small>EXPLORATORY RESEARCH · VERIFIED PUBLIC PROCESSED DATA</small><h1>Kidney cancer across RNA and protein</h1><p>'+headline+'</p><nav><a href="#findings">Findings</a><a href="#explore">Gene explorer</a><a href="#evidence">Evidence</a><a href="#methods">Methods</a></nav></header><section id="findings"><h2>What differs?</h2><p>'+interpret+'</p><p class="note">Each layer has its own scale. Significance differences are not tests of RNA–protein effect differences.</p><div class="grid">'+plots+'</div></section><section><h2>Six research candidates</h2><p>'+selection+'</p>'+table+'<p>Δ = tumor minus matched normal. CIs are pointwise. “—” means undefined; VEGFA protein is descriptive only.</p></section><section id="explore"><h2>Explore all aggregate gene results</h2><label>Gene <input id="search" placeholder="e.g. CA9" aria-label="Gene search"></label><label>Layer <select id="layer"><option value="">Both</option><option>protein</option><option>rna</option></select></label><label><input type="checkbox" id="sig"> BH q &lt; 0.05 only</label><p id="count"></p><div id="geneTable"></div><button id="prev">Previous</button><button id="next">Next</button><p class="muted">Click a column heading to sort. All rows embedded locally; 40 shown per page.</p></section><section id="evidence"><h2>Target–evidence matrix</h2><p>Live UniProt / Reactome annotations and Open Targets snapshots. Annotation is not enrichment. Drug stages are reproduced database labels across all indications; no kidney efficacy or current approval inference.</p>'+mt+'<h3>Evidence beyond the original cohort</h3><p>Clark et al. (2019), PMID 31675502, is the original cohort and is not counted as independent evidence. Records below were assessed at title/abstract level.</p><ul>'+sourcehtml+'</ul></section><section id="methods"><h2>Design, missingness and uncertainty</h2><p>'+methods+'</p><p>'+checks+'</p><p class="note">'+limitations+'</p><h3>Unresolved issues</h3><p>MNAR sensitivity and batch adjustment need defensible additional information. Full-text overlap and selectivity checks remain undone. MT1H has no independent target-specific record in this bounded review. Independent review remains pending. Two 503 responses are preserved; replacement searches succeeded. Unrelated PMID 17476008 was rejected after content review.</p><h3>Reproducibility</h3><p><a href="report.md">Concise report</a> · <a href="analysis_config.json">Configuration</a> · <a href="results.json">Results JSON</a> · <a href="outputs/protein_all_genes.csv">All proteins CSV</a> · <a href="outputs/rna_all_genes.csv">All RNA CSV</a> · <a href="analysis.py">Analysis script</a></p><details><summary>Raw-source provenance: URLs, UTC dates and checksums</summary><ul>'+provhtml+'</ul></details></section></main>'
js="""let rows=DATA,page=0,key='q',asc=true;const el=id=>document.getElementById(id);const cols=['gene','layer','n','mean_difference','ci95_low','ci95_high','p','q','status'];function render(){let a=rows.filter(r=>r.gene.toLowerCase().includes(el('search').value.toLowerCase())&&(!el('layer').value||r.layer===el('layer').value)&&(!el('sig').checked||(r.q!==null&&r.q<.05)));a.sort((x,y)=>x[key]===null?1:y[key]===null?-1:(typeof x[key]==='number'?x[key]-y[key]:String(x[key]).localeCompare(String(y[key])))*(asc?1:-1));page=Math.min(page,Math.max(0,Math.ceil(a.length/40)-1));el('count').textContent=a.length+' matching genes/layers · page '+(page+1);let t=document.createElement('table'),h=t.createTHead().insertRow();cols.forEach(c=>{let th=document.createElement('th');th.textContent=c;th.tabIndex=0;let f=()=>{asc=key===c?!asc:true;key=c;render()};th.onclick=f;th.onkeydown=e=>{if(e.key==='Enter')f()};h.appendChild(th)});let b=t.createTBody();a.slice(page*40,(page+1)*40).forEach(r=>{let tr=b.insertRow();cols.forEach(c=>{let v=r[c];tr.insertCell().textContent=v===null?'—':typeof v==='number'&&!Number.isInteger(v)?v.toPrecision(4):v})});el('geneTable').replaceChildren(t)}['search','layer','sig'].forEach(id=>el(id).oninput=()=>{page=0;render()});el('prev').onclick=()=>{page=Math.max(0,page-1);render()};el('next').onclick=()=>{page++;render()};render();"""
page+='<script>'+js.replace('DATA',json.dumps(allrows,separators=(',',':')).replace('</','<\\/'))+'</script></html>';(P/'report.html').write_text(page)
(P/'DECISIONS.md').write_text('# Follow-up state\n\n'+methods+'\n\n'+selection+'\n\nVerified fingerprint: '+cfg['input_fingerprint']+'. Main cohort n=72. Do not inspect other arms. No delegation, installs, MCP, runtime or SQLite used. No scientific approval claimed.\n\nRead report.md, analysis_config.json, method_review.json, sources/evidence_records.json and sources/source_manifest.json first. Raw data remain unchanged. Rerun commands in report.md. Current results: protein tested 10033; RNA tested 19015; zero-variance RNA 260; VEGFA protein n=1. Historical NDUFA4L2 → COXFA4L2 mapping is explicit.\n\nNext work: independent artifact review; verify full-text cohort independence for NNMT/NDUFA4L2; orthogonal assays; detailed batch/provenance audit; justify any MNAR sensitivity before implementing it. No clinical efficacy conclusion from expression.\n')
print('Report built; literature records:',len(evidence),'embedded aggregate rows:',len(allrows))
